name: Deploy Project
on: 
  push:
  workflow_dispatch:
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm i
      - name: Build
        run: npm run build
      - name: up;oad dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist-folder
          path: dist/
  deploy:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist-folder
      - name: List all files
        run: ls -R
      - name: deploy
        run: echo "Deploying..."