name: ESLint
on:
  pull_request:
    type:
      - opened
jobs:
  lint:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Use repo variable
        run: echo "API URL:${{ vars.API_URL }}"
      - name: Use repo secret
        run: echo "API KEY:${{ secrets.API_KEY }}"
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm i
      - name: Run ESLint
        run: npm run lint
